/**
 * fecha de creacion: junio de 2018
 * nombre: FDistribuidor
 * Su función mantenedor autores
 * entrada nombre distribuidor
 * salida null
 * @author: braulio valdes 
 */
package vista;

import controlador.ControladorAutores;
import controlador.ControladorCompras;
import controlador.ControladorDistribuidor;
import controlador.ControladorLibros;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.Compras;
import modelo.Distribuidores;
import modelo.Libros;

/**
 *
 * @author BRAULIOMARIANO
 */
public class FDistribuidor extends javax.swing.JFrame {
    /**
     * Creates new form FCategoria
     */
    
    DefaultComboBoxModel comboDistribuidor; 
    int suEstado;
    Calendar cal = Calendar.getInstance();
    
    public FDistribuidor() {
        initComponents();
        //this.setAlwaysOnTop(true);
        this.setLocationRelativeTo(null);
        txtYear.setEditable(false);
        txtEstado.setEditable(false);
        String fechaHoy = cal.get(Calendar.DATE)+"/"+cal.get(Calendar.MONTH)+"/"+cal.get(Calendar.YEAR);
        poblarYear();
        limpiar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAgrega = new javax.swing.JButton();
        txtRut = new javax.swing.JTextField();
        btnBorrar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        cmbDistribuidor = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtDv = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        cmbYear = new javax.swing.JComboBox<>();
        txtYear = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnCerrar1 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("MANTENEDOR DISTRIBUIDOR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 11, -1, -1));

        jLabel2.setText("RUT");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 59, -1, -1));

        btnAgrega.setText("Agrega");
        btnAgrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 215, -1, -1));

        txtRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutActionPerformed(evt);
            }
        });
        txtRut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRutKeyPressed(evt);
            }
        });
        getContentPane().add(txtRut, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 56, 81, -1));

        btnBorrar.setText("Cambia Estado");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 215, -1, -1));

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 215, -1, -1));

        btnModificar.setText("Actualizar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 215, -1, -1));

        cmbDistribuidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDistribuidorActionPerformed(evt);
            }
        });
        getContentPane().add(cmbDistribuidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 56, 237, -1));

        jLabel3.setText("Dirección");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 119, -1, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 85, 401, -1));

        txtDv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDvActionPerformed(evt);
            }
        });
        getContentPane().add(txtDv, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 56, 28, -1));

        jLabel4.setText("-");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 59, -1, -1));

        jLabel5.setText("Busca");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 59, -1, -1));

        jLabel6.setText("Nombre");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 88, -1, -1));
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 116, 401, -1));

        jLabel7.setText("Teléfono");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel8.setText("Año Incorporación");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 150, -1, -1));
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 147, 130, -1));

        cmbYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbYearActionPerformed(evt);
            }
        });
        getContentPane().add(cmbYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 147, 63, -1));
        getContentPane().add(txtYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 147, 63, -1));
        getContentPane().add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 178, 130, -1));

        jLabel9.setText("Estado");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 181, -1, -1));

        btnCerrar1.setText("Limpiar");
        btnCerrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 215, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 0, 0));
        jLabel27.setText("*");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 20, 10));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 0, 0));
        jLabel28.setText("*");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 20, 10));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 0, 0));
        jLabel29.setText("*");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 20, 10));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 0, 0));
        jLabel30.setText("*");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 20, 10));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 0, 0));
        jLabel31.setText("*");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 20, 10));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 0, 0));
        jLabel32.setText("*");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 20, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

           
    
    
    
    private void btnAgregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregaActionPerformed
        // TODO add your handling code here:
        // aqui agrega distribuidores
                
        if (txtRut.getText().isEmpty() || txtDv.getText().isEmpty() || txtNombre.getText().isEmpty() 
                || txtDireccion.getText().isEmpty() || txtTelefono.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe ingresa todos los datos", "Error de Ingreso", 1);
        }else{
            if(esNumero(txtRut.getText())){
                int id_distribuidor_rut = Integer.parseInt(txtRut.getText());      
            
                String dv = txtDv.getText();
                String nombre = txtNombre.getText();
                String direccion = txtDireccion.getText();
                String telefono = txtTelefono.getText();
                int yearr = Integer.parseInt(txtYear.getText());
            
                if(txtEstado.getText().equals("VIGENTE")){
                    suEstado = 1;
                }else{
                    suEstado = 0;
                }
            ControladorDistribuidor d = new ControladorDistribuidor();
            Distribuidores distribuidor = d.leer(id_distribuidor_rut); //recupera objeto distribuidor si lo encuentra
            if (distribuidor != null) {
                JOptionPane.showMessageDialog(null, "Error!, RUT distribuidor existente", "Error de Ingreso", 1);
            }else{
                Distribuidores distribuidorNuevo = new Distribuidores(id_distribuidor_rut,dv,nombre,
                                    direccion,telefono,suEstado,yearr);
                if(d.agregar(distribuidorNuevo)){
                    JOptionPane.showMessageDialog(null, "Distribuidor creado exitosamente", "Ingreso Válido",1);    
                }else{
                    JOptionPane.showMessageDialog(null, "Distribuidor no fue creado", "Ingreso No Válido",1);
                }
            }
        
        limpiar();
        }else{
                JOptionPane.showMessageDialog(null, "RUT DEBE SER NUMERICO, revise la información", "",1);
            }
        }
    }//GEN-LAST:event_btnAgregaActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
                // aqui borrado de distribuidores
        
        if (suEstado > 0){
            //chequear que el distribuidor no este vinculado a una compra
            ControladorCompras cD = new ControladorCompras();
            //
            String d = txtRut.getText();
            if(esNumero(d)){
                int rut = Integer.parseInt(d);
                if(cD.leerDistribuidorEnCompras(rut)==null){
                    suEstado = 0;
                }else{
                    JOptionPane.showMessageDialog(null, "Distribuidor vinculado con Compra, no se puede eliminar", "",1);
                }
            }        
        }else{
            suEstado = 1;
        }
        muestraEstado();
    }//GEN-LAST:event_btnBorrarActionPerformed

    
    private void poblarYear(){
        int y = cal.get(Calendar.YEAR);        
        for(int i=y;i>2000;i--){
            cmbYear.addItem(String.valueOf(i));
        }  
    }
    
    private void limpiar(){
        poblarDistribuidores();
        btnModificar.setEnabled(false);
        btnAgrega.setEnabled(false);
        btnBorrar.setEnabled(false);
        txtRut.setEditable(true);
        txtDv.setEditable(true);
        txtRut.setText("");      
        txtDv.setText("");
        txtNombre.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtYear.setText("");
        txtEstado.setText("");
        txtNombre.setEnabled(false);
        txtDireccion.setEnabled(false);
        txtTelefono.setEnabled(false);
        txtYear.setEnabled(false);
        txtEstado.setEnabled(false);
        txtRut.setEditable(true);
        suEstado = 1;
    }
    
    
    private void poblarDistribuidores(){
        ControladorDistribuidor cd = new ControladorDistribuidor();
        ArrayList<Distribuidores> distribuidor = cd.consultarTodo();
        comboDistribuidor = new DefaultComboBoxModel();
        String estado;
        for (Distribuidores d : distribuidor) {
            if(d.getEstado()==1){
                estado = "vigente"; 
            }else{
                estado = "eliminado"; 
            }  
            comboDistribuidor.addElement(d.getNombre()+"("+d.getId_distribuidor_rut()+")"+"["+estado+"]");
            cmbDistribuidor.setModel(comboDistribuidor);
        }
    }
    
    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
     
       dispose();
       
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        
        if (txtRut.getText().isEmpty() || txtDv.getText().isEmpty() || txtNombre.getText().isEmpty() 
                || txtDireccion.getText().isEmpty() || txtTelefono.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe ingresa todos los datos", "Error de Ingreso", 1);
        }else{
            if(esNumero(txtRut.getText())){   
                int rut = Integer.parseInt(txtRut.getText());
                String dv = txtDv.getText();
                String nombre = txtNombre.getText();
                String direccion = txtDireccion.getText();
                String telefono = txtTelefono.getText();
                int yearr = Integer.parseInt(txtYear.getText());
                ControladorDistribuidor cD = new ControladorDistribuidor();
                Distribuidores distribuidor = cD.leer(rut); //recupera objeto distribuidor si lo encuentra
                if(distribuidor != null) {
                    //crea un registro para hacer la actualizacion
                    Distribuidores distribuidorModificado = new Distribuidores(rut,dv,nombre,
                                            direccion,telefono,suEstado,yearr);
                    if(cD.modificar(distribuidorModificado)){
                        JOptionPane.showMessageDialog(null, "Distribuidor modificado exitosamente", "Ingreso Válido",1);
                    }else{
                        JOptionPane.showMessageDialog(null, "Distribuidor no fue modificado", "Modificación No Válida",1);
                    }
                }
            }else{
                JOptionPane.showMessageDialog(null, "Rut inválido, debe ser número","",1);
            }
        }
        limpiar();
    }//GEN-LAST:event_btnModificarActionPerformed

    void muestraEstado(){
        if (suEstado<1){
            txtEstado.setText("ELIMINADO");
            txtEstado.setForeground(Color.red);
        }else{
            txtEstado.setText("VIGENTE");
            txtEstado.setForeground(Color.blue);
        }    
    }
    
    private boolean esNumero(String dato){
        try{
            int cambio = Integer.parseInt(dato);
            return true;
        }catch(NumberFormatException ex){
            return false;
        }
    }
    
    private String modulo11(String rut){
        
        int largo=rut.length();
        int f = 2;
        int acumulador = 0;
        while(largo>0){
            largo--;
            int m = Integer.parseInt(rut.substring(largo,largo+1));
            acumulador = acumulador + (m*f);
            f = f + 1;
            if (f > 7){
                f = 2;
            }
        }
   
        acumulador = acumulador % 11;                
        acumulador = 11 - acumulador;
        if (acumulador == 10){
            return "0";
        }
        if (acumulador == 11){
            return "K";
        }
        return String.valueOf(acumulador);
    }
    
    
    
    private void cmbDistribuidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDistribuidorActionPerformed
        // TODO add your handling code here:
        btnAgrega.setEnabled(false);
        btnModificar.setEnabled(true);
        btnBorrar.setEnabled(true);
        String d = cmbDistribuidor.getItemAt(cmbDistribuidor.getSelectedIndex());
        try{
            String nombreDistribuidor = d.substring(0,d.indexOf("("));
            txtNombre.setText(nombreDistribuidor);
            String rutDistribuidor = d.substring(d.indexOf("(") + 1, d.indexOf(")"));
            txtRut.setText(rutDistribuidor);
            
            String str_estado = d.substring(d.indexOf("[") + 1, d.indexOf("]"));
            int estado;
            if(str_estado.equals("vigente")){
                estado = 1;
            }else{
                estado = 0;
            }
            if(estado == 1){
                    txtEstado.setForeground(Color.blue);
                    txtEstado.setText("VIGENTE");
                }else{
                    txtEstado.setForeground(Color.red);
                    txtEstado.setText("ELIMINADO");
                }
            ControladorDistribuidor cD = new ControladorDistribuidor();
            Distribuidores dSeleccionado = cD.leer(Integer.parseInt(rutDistribuidor));
            if (dSeleccionado!=null){
                txtRut.setEditable(false);
                txtDireccion.setText(dSeleccionado.getDireccion());
                txtDv.setText(dSeleccionado.getDv_distribuidor());
                txtTelefono.setText(dSeleccionado.getTelefono());
                txtYear.setText(String.valueOf(dSeleccionado.getYear_incorporacion()));
                txtNombre.setEnabled(true);
                txtDireccion.setEnabled(true);
                txtTelefono.setEnabled(true);
                txtYear.setEnabled(true);
                txtEstado.setEnabled(true);
                                
            }
        }catch(NullPointerException e){
            txtRut.setText("");
        }  
    }//GEN-LAST:event_cmbDistribuidorActionPerformed

    private void cmbYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbYearActionPerformed
        // TODO add your handling code here:
        txtYear.setText(cmbYear.getItemAt(cmbYear.getSelectedIndex()));
        
    }//GEN-LAST:event_cmbYearActionPerformed

    private void txtRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_txtRutActionPerformed

    private void txtRutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRutKeyPressed
        // TODO add your handling code here:            
    }//GEN-LAST:event_txtRutKeyPressed

    private void txtDvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDvActionPerformed
        // TODO add your handling code here:
        if(esNumero(txtRut.getText())){
            String r = txtRut.getText();      
            String dvGenerado = modulo11(r);
            String dvIngresado = txtDv.getText();
            if (dvIngresado.equals(dvGenerado)){
                txtRut.setEditable(false);
                txtDv.setEditable(false);
                txtNombre.setEnabled(true);
                txtDireccion.setEnabled(true);
                txtTelefono.setEnabled(true);
                txtYear.setEnabled(true);
                txtEstado.setEnabled(true);
                btnAgrega.setEnabled(true);
                txtEstado.setText("VIGENTE");
                txtEstado.setForeground(Color.blue);
            }else{
                JOptionPane.showMessageDialog(null, "Error!, RUT ingresado no es válido","",1);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Error!, RUT debe ser numérico","",1);
        }
    }//GEN-LAST:event_txtDvActionPerformed

    private void btnCerrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrar1ActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnCerrar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FDistribuidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FDistribuidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FDistribuidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FDistribuidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FDistribuidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgrega;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnCerrar1;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cmbDistribuidor;
    private javax.swing.JComboBox<String> cmbYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDv;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
