/**
 * fecha de creacion: junio de 2018
 * nombre: FEditorial
 * Su función mantenedor editorial
 * entrada nombre editorial
 * salida null
 * @author: braulio valdes 
 */
package vista;

import controlador.ControladorEditorial;
import controlador.ControladorLibros;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.Autores;
import modelo.Editorial;
import modelo.Libros;

/**
 *
 * @author BRAULIOMARIANO
 */
public class FEditorial extends javax.swing.JFrame {

    /**
     * Creates new form FCategoria
     */
    
    DefaultComboBoxModel comboEditorial = new DefaultComboBoxModel();
    
    public FEditorial() {       
        initComponents();
        //this.setAlwaysOnTop(true);
        this.setLocationRelativeTo(null);
        poblarEditorial();
        //btnModificar.setEnabled(false);
        //btnBorrar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAgrega = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        btnCancela1 = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        cmbEditorial = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("MANTENEDOR EDITORIALES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 11, -1, -1));

        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 46, -1, -1));

        btnAgrega.setText("Agrega");
        btnAgrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 69, -1, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 43, 336, -1));

        btnModificar.setText("Renombra");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 69, -1, -1));

        btnCancela1.setText("Cerrar");
        btnCancela1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancela1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancela1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 69, -1, -1));

        btnBorrar.setText("Cambia estado");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 69, -1, -1));

        cmbEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEditorialActionPerformed(evt);
            }
        });
        getContentPane().add(cmbEditorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 118, 336, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 0, 0));
        jLabel27.setText("*");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 20, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregaActionPerformed
        // TODO add your handling code here:
     
        // aqui agrega editoriales
        if (txtNombre.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe ingresa editorial", "Error de Ingreso", 1);
        }else{
            String nombre = txtNombre.getText();      
            ControladorEditorial c = new ControladorEditorial();
            Editorial editorial = c.leer(nombre); //recupera objeto editorial si lo encuentra
            if (editorial != null) {
                JOptionPane.showMessageDialog(null, "Edtorial existente", "Error de Ingreso", 1);
            }else{
                if(c.agregar(nombre)){
                    JOptionPane.showMessageDialog(null, "Editorial creada exitosamente", "Ingreso Válido",1);
                    poblarEditorial();
                }else{
                    JOptionPane.showMessageDialog(null, "Editorial no fue creada", "Ingreso No Válido",1);
                }
            }
            txtNombre.setText("");
        }
    }//GEN-LAST:event_btnAgregaActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
                
        if (txtNombre.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe ingresa editorial", "Error de Ingreso", 1);
        }else{
            String nombre = txtNombre.getText();      
            ControladorEditorial c = new ControladorEditorial();
            Editorial editorial = c.leer(nombre); //recupera objeto editorial si lo encuentra
            if (editorial != null) {
                JOptionPane.showMessageDialog(null, "Moficación ya existe, no se registró cambio", "Error", 1);
            }else{
                // se modifica la editorial
                String e = cmbEditorial.getItemAt(cmbEditorial.getSelectedIndex());
                int id_editorial = Integer.parseInt(e.substring(e.indexOf("(") + 1, e.indexOf(")")));
               
                Editorial edt = new Editorial(id_editorial,nombre,true);
                if(c.modificar(edt)){
                        JOptionPane.showMessageDialog(null, "Editoial modificada exitosamente", "Ingreso Válido",1);
                        poblarEditorial();
                    }else{
                        JOptionPane.showMessageDialog(null, "Editorial no fue modificado", "Modificación No Válida",1);
                    }
            }
        } 
    
    }//GEN-LAST:event_btnModificarActionPerformed


    private void poblarEditorial(){
        ControladorEditorial c = new ControladorEditorial();
        ArrayList<Editorial> editorial = c.consultarTodo();
        comboEditorial = new DefaultComboBoxModel();
        String estado;
        for (Editorial e : editorial) {
          if(e.isEstado()){
             estado = "vigente"; 
          }else{
             estado = "borrado"; 
          }  
          comboEditorial.addElement(e.getNombre()+"("+e.getId_editorial()+")"+"["+estado+"]");
          cmbEditorial.setModel(comboEditorial);
        }
    }
    
       
    private void btnCancela1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancela1ActionPerformed
        // TODO add your handling code here:

        dispose();
    }//GEN-LAST:event_btnCancela1ActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        if (txtNombre.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe ingresa editorial", "Error de Ingreso", 1);
        }else{
            String nombre = txtNombre.getText();      
            ControladorEditorial c = new ControladorEditorial();
            //busca el editorial
            Editorial editorial = c.leer(nombre); //recupera objeto editorial si lo encuentra
            if (editorial != null) {
                //busca la editorial si esta utilizado en algún libro
                ControladorLibros lib = new ControladorLibros();
                //JOptionPane.showMessageDialog(null, "editorial a eliminar"+autores.getId_autor(), "Ingreso Válido",0);
                Libros libros = lib.leerEditorialEnLibro(editorial.getId_editorial()); 
                //recupera objeto libro si encuentra el autor
                if(libros!=null){
                    JOptionPane.showMessageDialog(null, "No es posible cambiar estado, esta vinculado a un libro", "no procesado",1);
                }else{
                    if(c.cambiaEstado(editorial.getId_editorial(),!(editorial.isEstado()))){
                        if(editorial.isEstado()){
                            JOptionPane.showMessageDialog(null, "Se cambio estado a "+"borrado", "Procesado",1);
                        }else{
                            JOptionPane.showMessageDialog(null, "Se cambio estado a "+"vigente", "Procesado",1);
                        }
                        poblarEditorial();
                       }
                    }
            }else{
                JOptionPane.showMessageDialog(null, "Editorial no existe", "Error de proceso", 1);
            }
            txtNombre.setText("");
        }  
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void cmbEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEditorialActionPerformed
        // TODO add your handling code here:
        
        String ed = cmbEditorial.getItemAt(cmbEditorial.getSelectedIndex());
        try{
            String editorial = ed.substring(0,ed.indexOf("("));
            txtNombre.setText(editorial);
            
        }catch(NullPointerException e){
            txtNombre.setText("");
        }

        
    }//GEN-LAST:event_cmbEditorialActionPerformed


    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FEditorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FEditorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FEditorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FEditorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FEditorial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgrega;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCancela1;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cmbEditorial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
