/**
 * fecha de creacion: junio de 2018
 * nombre: FVentasLibros
 * Su función ingreso de ventas de libros
 * entrada datos de la venta de libros
 * salida null
 * @author: braulio valdes 
 */
package vista;

import controlador.ControladorLibros;
import controlador.ControladorParametros;
import controlador.ControladorPersona;
import controlador.ControladorVentas;
import controlador.ControladorVentasDetalle;
import java.awt.Color;
import java.sql.Date;
import java.sql.Time;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import modelo.Libros;
import modelo.Parametros;
import modelo.Personas;
import modelo.Ventas;
import modelo.VentasDetalle;
import static vista.MenuPrincipalBiblioteca.cal;
import static vista.MenuPrincipalBiblioteca.diaSistema;
import static vista.MenuPrincipalBiblioteca.mesSistema;
import static vista.MenuPrincipalBiblioteca.yearSistema;

/**
 *
 * @author BRAULIOMARIANO
 */
public class FVentasLibros extends javax.swing.JFrame {
    
    //variable para almacenar libro creado en mantenedor de libros durante la compra
    
    FPersona fp = new FPersona();
    DefaultComboBoxModel comboClientes;
    DefaultComboBoxModel comboDependientes;
    DefaultListModel modelCL = new DefaultListModel();
    String hora, fechaHoy;
    Date fechaFactura;
    //folio Boleta Venta
    long folioBoletaVenta;
    int dia, mes, year, hVenta, mVenta, sVenta, totalVenta;
    int[] listaLibrosVendidos;
    int librosVendidos, antiguoStock, nuevoStock, nuevoPrecio, enArriendo;
    DefaultTableModel modelTableVentas;
    String [] titulos = {"Serie","Isbn","Titulo","Stock","Valor Venta"};
    String [] campos = new String [5];
    int ImpuestoIva, Descuento_especial,MontoMinimoDescuento;
    /**
     * Creates new form FComprasLibros
     */
    public FVentasLibros() {
        initComponents();
        //this.setAlwaysOnTop(true);
        this.getContentPane().setBackground(Color.LIGHT_GRAY);
        this.setLocationRelativeTo(null);
        lbFechaSistema.setText(String.valueOf(diaSistema)+"/"+String.valueOf(mesSistema)+"/"+String.valueOf(yearSistema));    

//      MenuPrincipalBiblioteca.procesoCompraLibro=false;
        cmbCuotas.setEnabled(false);
        txtTituloLibro.setEditable(false);
        txtNeto.setEditable(false);
        txtNeto.setEnabled(false);
        txtIva.setEditable(false);
        txtIva.setEnabled(false);
        txtTotal.setEditable(false);
        txtTotal.setEnabled(false);
        txtTituloLibro.setBackground(Color.orange);
        txtTituloLibro.setEditable(false);
        btnAgregaCliente.setEnabled(true);
        poblarFormaPago();
        poblarCuotas();
        poblarCalendario();
        txtCliente.setEditable(false);
        leerParametros();
        limpiar();
        //busca ultimo folio boleta
        buscarFolio(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField8 = new javax.swing.JTextField();
        txtFolio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbCliente = new javax.swing.JComboBox<>();
        btnActualizarCliente = new javax.swing.JButton();
        btnAgregaCliente = new javax.swing.JButton();
        cmbFormaPago = new javax.swing.JComboBox<>();
        cmbCuotas = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListLibros = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        txtSerie = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        txtTituloLibro = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtNeto = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnAgregarLibro = new javax.swing.JButton();
        btnRegistrarVenta = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cmbDia = new javax.swing.JComboBox<>();
        cmbMes = new javax.swing.JComboBox<>();
        cmbYear = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtGlosa = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        btnCambiaSerie = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        txtIva = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtDependiente = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cmbDependiente = new javax.swing.JComboBox<>();
        btnActualizarDependiente = new javax.swing.JButton();
        btnAgregaDependiente = new javax.swing.JButton();
        labelStock = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableLibrosVentas = new javax.swing.JTable();
        lbFechaSistema = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtSubtotalVenta = new javax.swing.JTextField();
        txtDescuento = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtTotalParcial = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(100, 50));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFolio.setBackground(new java.awt.Color(255, 255, 0));
        txtFolio.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtFolio.setForeground(new java.awt.Color(255, 0, 0));
        txtFolio.setCaretColor(new java.awt.Color(255, 0, 0));
        txtFolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFolioActionPerformed(evt);
            }
        });
        getContentPane().add(txtFolio, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 60, 117, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("BOLETA N°");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 70, -1, -1));

        txtCliente.setBackground(new java.awt.Color(204, 255, 255));
        txtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 300, -1));

        jLabel3.setText("Fecha Venta");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, -1, -1));

        jLabel4.setText("DESCUENTO ESPECIAL $");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, -1, -1));

        jLabel5.setText("IDENTIFIQUE CLIENTE");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 103, -1, -1));

        jLabel6.setText("Forma de Pago");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, -1, 20));

        jLabel7.setText("Número Cuotas");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, -1, 20));

        cmbCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClienteActionPerformed(evt);
            }
        });
        getContentPane().add(cmbCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 123, 305, -1));

        btnActualizarCliente.setText("@");
        btnActualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 50, 20));

        btnAgregaCliente.setText("+");
        btnAgregaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregaClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 123, -1, 20));

        cmbFormaPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFormaPagoActionPerformed(evt);
            }
        });
        getContentPane().add(cmbFormaPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, 110, -1));

        getContentPane().add(cmbCuotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 110, -1));

        jListLibros.setBackground(new java.awt.Color(204, 255, 204));
        jListLibros.setForeground(new java.awt.Color(51, 51, 51));
        jListLibros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListLibrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListLibros);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 510, 120));

        jLabel8.setText("REGISTRO LIBRO");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        txtSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerieActionPerformed(evt);
            }
        });
        txtSerie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSerieKeyReleased(evt);
            }
        });
        getContentPane().add(txtSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 133, -1));

        jLabel9.setText("CANTIDAD");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("<LIBROS EXISTENTES>");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 470, 150, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("<MANTENEDOR VENTAS LIBROS>");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 20, -1, -1));
        getContentPane().add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 72, -1));
        getContentPane().add(txtTituloLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 270, -1));

        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 72, -1));

        jLabel12.setText("SERIE LIBRO");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        txtNeto.setBackground(new java.awt.Color(204, 255, 255));
        txtNeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNetoActionPerformed(evt);
            }
        });
        getContentPane().add(txtNeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 570, 110, 30));

        jLabel13.setText("TITULO LIBRO");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        jLabel14.setText("(IVA INCLUIDO)");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, -1, -1));

        btnAgregarLibro.setText("AGREGA LIBRO >>>");
        btnAgregarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarLibroActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 140, -1));

        btnRegistrarVenta.setText("Registrar Venta");
        btnRegistrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVentaActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 180, 130, 40));

        btnLimpiar.setText("Limpiar Campos");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 220, 130, 40));

        jButton3.setText("Cerrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 260, 130, 40));

        cmbDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDiaActionPerformed(evt);
            }
        });
        getContentPane().add(cmbDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, -1, -1));

        cmbMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMesActionPerformed(evt);
            }
        });
        getContentPane().add(cmbMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, -1, -1));

        cmbYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbYearActionPerformed(evt);
            }
        });
        getContentPane().add(cmbYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, -1, -1));

        jLabel16.setText("/");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, -1, -1));

        jLabel17.setText("/");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, -1, -1));

        txtGlosa.setBackground(new java.awt.Color(204, 255, 204));
        txtGlosa.setColumns(20);
        txtGlosa.setRows(5);
        jScrollPane2.setViewportView(txtGlosa);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 330, 57));

        jLabel15.setText("GLOSA");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, -1, -1));

        btnCambiaSerie.setText("CAMBIA SERIE");
        btnCambiaSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiaSerieActionPerformed(evt);
            }
        });
        getContentPane().add(btnCambiaSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 130, -1));

        jLabel20.setText("PRECIO UNITARIO $");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, -1));

        txtTotal.setBackground(new java.awt.Color(204, 255, 255));
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 630, 110, 30));

        txtIva.setBackground(new java.awt.Color(204, 255, 255));
        txtIva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIvaActionPerformed(evt);
            }
        });
        getContentPane().add(txtIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 600, 110, 30));

        jLabel21.setText("TOTAL $");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 640, -1, -1));

        jLabel22.setText("19% IVA $");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 610, -1, -1));

        txtDependiente.setBackground(new java.awt.Color(204, 255, 255));
        txtDependiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDependienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtDependiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 300, -1));

        jLabel18.setText("IDENTIFIQUE DEPENDIENTE");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 201, -1, -1));

        cmbDependiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDependienteActionPerformed(evt);
            }
        });
        getContentPane().add(cmbDependiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 221, 305, -1));

        btnActualizarDependiente.setText("@");
        btnActualizarDependiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarDependienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizarDependiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 50, 20));

        btnAgregaDependiente.setText("+");
        btnAgregaDependiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregaDependienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregaDependiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 221, -1, 20));

        labelStock.setBackground(new java.awt.Color(255, 255, 255));
        labelStock.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelStock.setForeground(new java.awt.Color(0, 0, 255));
        labelStock.setText("STOCK LIBRO");
        getContentPane().add(labelStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 151, -1));

        jTableLibrosVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableLibrosVentas.setEnabled(false);
        jTableLibrosVentas.setRowSelectionAllowed(false);
        jTableLibrosVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLibrosVentasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableLibrosVentas);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 488, 510, 190));

        lbFechaSistema.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbFechaSistema.setForeground(new java.awt.Color(0, 0, 255));
        lbFechaSistema.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(lbFechaSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("<DETALLE DE LIBROS INCLUIDOS EN VENTA>");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 350, -1));
        getContentPane().add(txtSubtotalVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 530, 110, 30));

        txtDescuento.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtDescuento.setForeground(new java.awt.Color(0, 0, 255));
        getContentPane().add(txtDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 110, 30));

        jLabel23.setText("NETO  $");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 580, -1, -1));

        jLabel24.setText("SUBTOTAL $");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, -1, -1));

        txtTotalParcial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalParcialActionPerformed(evt);
            }
        });
        getContentPane().add(txtTotalParcial, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, 110, 30));

        jLabel25.setText("TOTAL $");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 540, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 0, 0));
        jLabel26.setText("*");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 20, 10));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 0, 0));
        jLabel27.setText("*");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 20, 10));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 0, 0));
        jLabel28.setText("*");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 20, 10));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 0, 0));
        jLabel29.setText("*");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 20, 10));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 0, 0));
        jLabel30.setText("*");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 20, 10));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 0, 0));
        jLabel31.setText("*");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 20, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void leerParametros(){
        ControladorParametros c = new ControladorParametros();
        Parametros p = c.leer(1);
        if(p==null){
            c.agregar();
        }else{
            ImpuestoIva=p.getImpuesto_iva();
            Descuento_especial=p.getDescuento_especial();
            MontoMinimoDescuento=p.getMonto_minimo_descuento();
        }
    }
    
    
    private void limpiar(){
        poblarClientes();
        poblarDependientes();
        txtGlosa.setText("");
        txtFolio.setText("");
        txtNeto.setText("");
        txtIva.setText("");
        txtTotal.setText("");
        txtTituloLibro.setText("");
        txtSerie.setText("");
        txtPrecio.setText("");
        txtCantidad.setText("");
        txtCliente.setText("");
        txtDependiente.setText("");
        txtGlosa.setEnabled(false);
        txtSerie.setEnabled(false);
        txtSerie.setEnabled(false);
        txtPrecio.setEnabled(false);
        txtCantidad.setEnabled(false);
        cmbFormaPago.setEnabled(false);
        cmbCuotas.setEnabled(false);
        cmbDia.setEnabled(false);
        cmbMes.setEnabled(false);
        cmbYear.setEnabled(false);
        txtTituloLibro.setEnabled(false);
        btnAgregarLibro.setEnabled(false);
        btnCambiaSerie.setEnabled(false);
        txtFolio.setEnabled(true);   
        btnRegistrarVenta.setEnabled(false);
        btnLimpiar.setEnabled(false);
        modelCL.clear();
        librosVendidos=0;
        txtGlosa.setEnabled(true);
        txtFolio.setEditable(false);
        txtNeto.setEnabled(true);
        txtIva.setEnabled(true);
        txtTotal.setEnabled(true);
        txtSerie.setEnabled(true);
        cmbFormaPago.setEnabled(true);
        cmbDia.setEnabled(true);
        cmbMes.setEnabled(true);
        cmbYear.setEnabled(true);
        btnAgregarLibro.setEnabled(true);
        btnCambiaSerie.setEnabled(true);
        btnActualizarCliente.setEnabled(true);
        btnAgregaCliente.setEnabled(true);
        btnLimpiar.setEnabled(true);
        btnRegistrarVenta.setEnabled(true);
        txtSerie.setEditable(true);
        btnLimpiar.setEnabled(false);
        jTableLibrosVentas.setEnabled(true);
        llenarTablaConLibros("titulo","");
    }
    
    void llenarTablaConLibros(String campo, String buscado){
        int stockReal;
        modelTableVentas = new DefaultTableModel(null,titulos);
        ControladorLibros clibros = new ControladorLibros();
        ArrayList<Libros> lib;
        if (campo.equals("titulo")){
            lib = clibros.consultarTodoParametroTitulo(buscado);
        }else{
            lib = clibros.consultarTodoParametroSerie(buscado);
            }
        if(lib!=null){
            int largo=lib.size();
            while (largo>0){
                stockReal=lib.get(largo-1).getStock()-lib.get(largo-1).getEnArriendo();
                //extrae datos del arraylist para poblar tabla libros                
                //Serie-Isbn-Titulo-Editorial-Autor-Idioma-Stock-Estado-$Venta-$Arriendo
                
                campos[0]=lib.get(largo-1).getSerie();
                campos[1]=lib.get(largo-1).getIsbn();
                campos[2]=lib.get(largo-1).getTitulo();
                campos[3]=String.valueOf(stockReal);
                campos[4]=String.valueOf(lib.get(largo-1).getPrecioVenta());
                modelTableVentas.addRow(campos);    
                largo--;
            }
         jTableLibrosVentas.removeAll();
         jTableLibrosVentas.setModel(modelTableVentas);
                 //ALINEA CELDAS TABLAS
         DefaultTableCellRenderer alinear = new DefaultTableCellRenderer();
         alinear.setHorizontalAlignment(SwingConstants.RIGHT);//.LEFT .RIGHT .CENTER
         jTableLibrosVentas.getColumnModel().getColumn(0).setCellRenderer(alinear);
         jTableLibrosVentas.getColumnModel().getColumn(1).setCellRenderer(alinear);
         jTableLibrosVentas.getColumnModel().getColumn(2).setCellRenderer(alinear);
         jTableLibrosVentas.getColumnModel().getColumn(3).setCellRenderer(alinear);
         jTableLibrosVentas.getColumnModel().getColumn(4).setCellRenderer(alinear);
        }
    }

    
    
    private void buscarFolio(){
        ControladorVentas cVentas = new ControladorVentas();
        folioBoletaVenta = cVentas.buscarFolio(); 
        folioBoletaVenta++;
        String formatoFolio="00000"+String.valueOf(folioBoletaVenta).trim();
        int x = formatoFolio.length();
        txtFolio.setText(formatoFolio.substring(x-6,x));

    }
    
    
    private void poblarCalendario(){
        try{
            for(int d=1;d<32;d++){
                cmbDia.addItem(String.valueOf(d));
            }
            for(int m=1;m<13;m++){
                cmbMes.addItem(String.valueOf(m));
            }
    
            for(int a=yearSistema;a>2000;a--){
                cmbYear.addItem(String.valueOf(a));
            }
            cmbDia.setSelectedIndex(diaSistema-1);
            cmbMes.setSelectedIndex(mesSistema-1);
            cmbYear.setSelectedIndex(0);
        }catch(Exception e){
            //JOptionPane.showMessageDialog(null, "fecha:"+diaSistema+"/"+mesSistema+"/"+yearSistema, "",0);
        }
    }
    
    private DefaultListModel modelListA(String libroComprado){
   
        int l = modelCL.getSize();
        boolean existe = false;
        
        // el valor del item libro es sumado o restado al acumualor

        String lC = libroComprado;
        int largo = lC.length();
        int subTotal = 0;
        String valorItem = lC.substring(lC.indexOf("+")+2,largo).trim();
        if(esNumero(valorItem)){
            subTotal = Integer.parseInt(valorItem);
        }
        
        // controla que siempre haya un autor seleccionado
        while(l>0){
            if (modelCL.get(l-1).equals(libroComprado)){
                existe = true;
                break;
            }
            l--;
        }
        if (existe){
            modelCL.removeElement(libroComprado);
            librosVendidos--;
            totalVenta = totalVenta - subTotal;
        }else{
            modelCL.addElement(libroComprado);
            librosVendidos++;
            totalVenta = totalVenta + subTotal;
        }       
        calculaTotalFactura(totalVenta);
        if(librosVendidos<1){
            cambiarSerie();
        }
        return modelCL;
        
    }
    
    private void poblarFormaPago(){
        cmbFormaPago.addItem("Efectivo");
        cmbFormaPago.addItem("Cheque");
        cmbFormaPago.addItem("Cuotas");
    }
    
    private void poblarCuotas(){
        cmbCuotas.addItem("3 cuotas Precio Contado");
        cmbCuotas.addItem("6 cuotas Precio Contado");
    }
    
    private void poblarClientes(){
        ControladorPersona cD = new ControladorPersona();
        ArrayList<Personas> lista = cD.consultarTodo();
        comboClientes = new DefaultComboBoxModel();
        String estado;
        for (Personas p : lista) {
            // dependiente = 1
            if(p.getTipo_persona()!=1){  
                if(p.getEstado()==1){
                    estado = "vigente"; 
                    comboClientes.addElement(p.getNombre()+"("+p.getId_persona_rut()+")"+"["+estado+"]");
                    cmbCliente.setModel(comboClientes);
                }
            }
        }        
    }
    
    
    private void poblarDependientes(){
        ControladorPersona cD = new ControladorPersona();
        ArrayList<Personas> lista = cD.consultarTodo();
        comboDependientes = new DefaultComboBoxModel();
        String estado;
        for (Personas p : lista) {
            // cliente = 0
            if(p.getTipo_persona()>0){
                if(p.getEstado()==1){
                    estado = "vigente"; 
           
                    comboDependientes.addElement(p.getNombre()+"("+p.getId_persona_rut()+")"+"["+estado+"]");
                    cmbDependiente.setModel(comboDependientes);
                }
            }    
        }        
    }
    
    
    private void btnActualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarClienteActionPerformed
        // TODO add your handling code here:
        poblarClientes();
    }//GEN-LAST:event_btnActualizarClienteActionPerformed

    private void btnAgregaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregaClienteActionPerformed
        // TODO add your handling code here:
        
        if (!fp.isVisible()){
            fp.setVisible(true);    
        }
        
        
    }//GEN-LAST:event_btnAgregaClienteActionPerformed

    private boolean validaFecha(){
        int topeDiaMes=0;
            
        if(mes==1 || mes==3 || mes==5 || mes==7 || mes ==8 || mes==10 || mes==12){
            topeDiaMes = 31;
        }
        if(mes==4 || mes==6 || mes==9 || mes ==11){
            topeDiaMes = 30;
        }
        if(mes==2){
            topeDiaMes = 28;
        }
        if((year%4==0) & mes==2){
            topeDiaMes = 29;    
        }
        if(dia>topeDiaMes){
            return false;
        }
        return true;
    }
    
    
    private void btnAgregarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarLibroActionPerformed
        // TODO add your handling code here:

        if(!esNumero(txtSerie.getText()) || !esNumero(txtPrecio.getText()) || 
                    !esNumero(txtCantidad.getText()) || txtTituloLibro.getText().isEmpty()){
            // error numeros o titulo vacios por no elección de libro
            if(txtTituloLibro.getText().isEmpty()){
                // se cancelo la creación de libro nuevo
                cambiarSerie();
            }else{
                JOptionPane.showMessageDialog(null, "Atención!, Sólo se aceptan valores númericos", "",1);
                txtSerie.setFocusable(true);
            }        
        }else{
            try{
                // verifica stock a rebajar segun cantidad ngresafda
                String serieLibro = txtSerie.getText();
                int librosUtilizados = antiguoStock - enArriendo;
                int cantidad = Integer.parseInt(txtCantidad.getText());
                if (librosUtilizados<cantidad){
                    JOptionPane.showMessageDialog(null, "Atención!, el libro: "+serieLibro+" sin Stock", "",1);
                    txtSerie.setFocusable(true);
                }else{
                    // controla conversion de numeros
                    
                    int precio = Integer.parseInt(txtPrecio.getText());
                    int subTotal = precio * cantidad;
                    calculaTotalFactura(subTotal);
                    String libro="";
                    // formatea titulo de libros
 
                    String titulo = txtTituloLibro.getText();
                    int lt = titulo.length();
                    if (lt>20){
                        libro = titulo.substring(0, 21);
                    }else{
                        libro = titulo.format("%-20s", titulo);
                    }
                    String p = String.valueOf(precio);
                    String c = String.valueOf(cantidad);        
                    String s = String.valueOf(subTotal);
                        
                    String cantidadLibro = c.format("%-5s", c);
                    String precioLibro = p.format("%-10s", p);
                    String subtotalLibro = s.format("%-15s", s);
                    String libroComprado = libro+"("+serieLibro+")"+" #"+cantidadLibro+"$"+precioLibro+"+$"+subtotalLibro;                          
                    jListLibros.setModel(modelListA(libroComprado));
                    btnLimpiar.setEnabled(true);
                    cambiarSerie();
                    txtCantidad.setText("");
                    txtPrecio.setText("");
                    txtTituloLibro.setText("");
                    txtSerie.setText("");
                }   
            }catch(Exception ex){
                    JOptionPane.showMessageDialog(null, "Atención!, Revise cantidad ingresadas", "",1);
            }
            
        }
    }//GEN-LAST:event_btnAgregarLibroActionPerformed
        
    private void calculaTotalFactura(int total){
        txtTotalParcial.setText(String.valueOf(total));
        txtTotalParcial.setHorizontalAlignment(JTextField.RIGHT);
        int netoSinDescuento, descuento, netoVenta, ivaVenta, totalVenta;
        int totalFactura = total;
        int rebaja=0;
        float divisor = 100f;
        float porciento=1f;
        float fTotal;
        float porcentajeDescuento;
        float desc=0;
        float nuevoTotal;
        float ivaParametro;
        float netoReal;
        
        if(totalFactura>=MontoMinimoDescuento){
            fTotal = (float)totalFactura;
            porcentajeDescuento = (float)Descuento_especial;
            porcentajeDescuento = porcentajeDescuento / divisor;
            
            desc = fTotal * porcentajeDescuento;
            nuevoTotal = fTotal - desc;            
            totalFactura = (int)nuevoTotal;
            rebaja = (int)desc;
        }
        
        fTotal = (float)totalFactura;
        ivaParametro = (float)ImpuestoIva;
        ivaParametro = ivaParametro / divisor;
        ivaParametro = ivaParametro + porciento;

        netoReal = fTotal / ivaParametro;
        totalVenta = (int)fTotal;
        netoVenta = (int)netoReal;
       
        ivaVenta = totalVenta - netoVenta;
        
        
        txtSubtotalVenta.setText(String.valueOf(totalFactura));
        txtDescuento.setText(String.valueOf(-rebaja));        
        txtNeto.setText(String.valueOf(netoVenta));
        txtIva.setText(String.valueOf(ivaVenta));
        txtTotal.setText(String.valueOf(totalVenta));
        txtTotal.setHorizontalAlignment(JTextField.RIGHT);
        txtSubtotalVenta.setHorizontalAlignment(JTextField.RIGHT);
        txtDescuento.setHorizontalAlignment(JTextField.RIGHT);
        txtNeto.setHorizontalAlignment(JTextField.RIGHT);
        txtIva.setHorizontalAlignment(JTextField.RIGHT); 
        
    }   

        
        
    private boolean esNumero(String dato){
        try{
            int cambio = Integer.parseInt(dato);
            if(cambio==0){
                return false;
            }
            return true;
        }catch(NumberFormatException ex){
            return false;
        }
    }
    
    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        // TODO add your handling code here:
        
        txtCliente.setText(cmbCliente.getItemAt(cmbCliente.getSelectedIndex()));
        
    }//GEN-LAST:event_txtClienteActionPerformed

    private void cmbFormaPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFormaPagoActionPerformed
        // TODO add your handling code here:
        if(cmbFormaPago.getItemAt(cmbFormaPago.getSelectedIndex()).equals("Cuotas")){
            cmbCuotas.setEnabled(true);
        }else{
            cmbCuotas.setEnabled(false);
        }
    }//GEN-LAST:event_cmbFormaPagoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        limpiar();
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnRegistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVentaActionPerformed
        // TODO add your handling code here:
        if(validaFecha()){   
            if(txtFolio.getText().isEmpty() || txtTotal.getText().isEmpty() || txtNeto.getText().isEmpty() ||
                 txtNeto.getText().isEmpty() || txtGlosa.getText().isEmpty() || modelCL.size() < 1){
                JOptionPane.showMessageDialog(null, "Atención!, debe completar todos los datos", "",1);
            }else{
                if(esNumero(txtFolio.getText()) ){
                    String cCliente = txtCliente.getText();
                    int id_cliente = Integer.parseInt(cCliente.substring(cCliente.indexOf("(") + 1, cCliente.indexOf(")"))); 
                    String cDependiente = txtDependiente.getText();
                    int id_dependiente = Integer.parseInt(cDependiente.substring(cDependiente.indexOf("(") + 1, cDependiente.indexOf(")"))); 
                    ControladorVentas cV = new ControladorVentas();
                    if(cV.leer(folioBoletaVenta)!=null){
                        JOptionPane.showMessageDialog(null, 
                                "Atención!, Compra ya registrada según Folio Boleta", "",1);
                    }else{
                        // COMPRA Y FACTURA NUEVA
                        int folio = Integer.parseInt(txtFolio.getText());
                        int total = Integer.parseInt(txtTotal.getText());
                        //int titulo = Integer.parseInt(txtTitulo.getText());
                        String serie = txtSerie.getText();
                        int fpago, cuotas = 1;
                        String glosa = txtGlosa.getText();
                        if(cmbFormaPago.getItemAt(cmbFormaPago.getSelectedIndex()).equals("Efectivo")){
                            fpago = 1;
                        }else{
                            if(cmbFormaPago.getItemAt(cmbFormaPago.getSelectedIndex()).equals("Cheque")){
                                fpago = 2;
                        }else{
                                fpago = 3;
                                if(cmbCuotas.getItemAt(cmbCuotas.getSelectedIndex()).equals("3 cuotas Precio Contado")){
                                    //
                                    cuotas = 3;
                                }else{
                                    //
                                    cuotas = 6;
                                }
                            }
                        }
                        
                        dia = Integer.parseInt(cmbDia.getItemAt(cmbDia.getSelectedIndex()));
                        mes = Integer.parseInt(cmbMes.getItemAt(cmbMes.getSelectedIndex()));
                        year = Integer.parseInt(cmbYear.getItemAt(cmbYear.getSelectedIndex()));
                        fechaHoy = cal.get(Calendar.DATE)+"/"+cal.get(Calendar.MONTH)+"/"+cal.get(Calendar.YEAR);
                        //hora = cal.get(Calendar.HOUR_OF_DAY)+":"+cal.get(Calendar.MINUTE)+":"+cal.get(Calendar.SECOND);
                        hVenta = cal.get(Calendar.HOUR_OF_DAY);
                        mVenta = cal.get(Calendar.MINUTE);
                        sVenta = cal.get(Calendar.SECOND);
                        String laHora = String.valueOf(hVenta)+":"+String.valueOf(mVenta)+":"+String.valueOf(sVenta);
                        
                        Time hora = Time.valueOf(laHora);
         
                        Ventas nuevaVenta= new Ventas(folioBoletaVenta,total,dia,mes,year,
                                   hora, fpago,id_cliente,id_dependiente,cuotas,glosa, librosVendidos);
                        
                        if(cV.agregar(nuevaVenta)){
                            //recupera id generado por nueva compra, busca por folio y distribuidor
                            ControladorVentasDetalle cVentasDetalle = new ControladorVentasDetalle();
                            // grabar libros compralibro
                            int serieLibro, cantidad, precio;
                            
                            while(librosVendidos>0){
                                //serieLibro=listaLibrosComprados[librosComprados-1];
                                String libroVendido = modelCL.get(librosVendidos-1).toString();
                                serieLibro = Integer.parseInt((libroVendido.substring(libroVendido.indexOf("(") + 1, libroVendido.indexOf(")"))).trim());
                                cantidad = Integer.parseInt((libroVendido.substring(libroVendido.indexOf("#") + 1, libroVendido.indexOf("$"))).trim());
                                precio = Integer.parseInt((libroVendido.substring(libroVendido.indexOf("$") + 1, libroVendido.indexOf("+"))).trim());
                                String tituloLibro = libroVendido.substring(0, libroVendido.indexOf("(")).trim(); 
                                //serie string pra consulta existencia
                                String str_Serie = String.valueOf(serieLibro);
                                
                                
                                //consulta stock
                                ControladorLibros cLibros = new ControladorLibros();
                                
                                    //actualiza stock
                                    
                                    nuevoStock = antiguoStock - cantidad;
                                    nuevoPrecio = precio;
                                    if(!cLibros.actualizaStockYprecio(str_Serie, nuevoStock, nuevoPrecio)){
                                        //error no se actuliza stock
                                        JOptionPane.showMessageDialog(null, "OCURRIO UN ERROR, NO SE ACTUALIZO STOCK LIBRO", "",1);
                                    }
                                    
                                //graba libros vinculados a la venta
                                //se almacena cantidad y precio de cada libro comprado
                                
                                VentasDetalle ventasDetalle = new VentasDetalle(folioBoletaVenta,str_Serie.trim(),cantidad,precio);
                               
                                if(cVentasDetalle.agregar(ventasDetalle)){
                                    //se graba libro vinvulado a venta
                                    //
                                    //JOptionPane.showMessageDialog(null, "VINCULO LIBRO "+str_Serie+" A COMPRA", "",0);
                                }else{
                                    JOptionPane.showMessageDialog(null, "ERROR AL INTENTAR GRABAR "+ventasDetalle, "",1);
                                    }
                                
                                librosVendidos--;
                            }
                            librosVendidos=0;
                            // grabacion exitosa
                            //busca ultimo folio boleta
                            buscarFolio(); 
                            JOptionPane.showMessageDialog(null, 
                                    "COMPRA EXITOSA ("+hVenta+":"+mVenta+":"+sVenta+" Hr.)", "",1);
                            limpiar();
                        }else{
                            // no fue posible grabar
                            JOptionPane.showMessageDialog(null, "Error!, NO SE REGISTRO COMPRA", "",1);
                        }
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Atención!, la SERIE debe ser numérico y positivo", "",1);
                    txtSerie.setFocusable(true);
                }    
            }
            }else{
                // fecha no válida
                JOptionPane.showMessageDialog(null, "Atención!, Fecha no válida", "",1);
                cmbDia.setFocusable(true);
        }   
    }//GEN-LAST:event_btnRegistrarVentaActionPerformed

    private void poblarLibrosVendidos(){
    
    listaLibrosVendidos = new int[librosVendidos];
    while(librosVendidos>0){
            String l = modelCL.get(librosVendidos-1).toString();
            int serieLibro = Integer.parseInt(l.substring(l.indexOf("(") + 1, l.indexOf(")")));
            listaLibrosVendidos[librosVendidos-1]=serieLibro;
            librosVendidos--;
        }
}
    
    
    private void cmbYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbYearActionPerformed
        // TODO add your handling code here:
        
        year = Integer.parseInt(cmbYear.getItemAt(cmbYear.getSelectedIndex()));
        
    }//GEN-LAST:event_cmbYearActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
      
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void cmbDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDiaActionPerformed
        // TODO add your handling code here:
        
        dia = Integer.parseInt(cmbDia.getItemAt(cmbDia.getSelectedIndex()));
        
        
    }//GEN-LAST:event_cmbDiaActionPerformed

    private void cmbMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMesActionPerformed
        // TODO add your handling code here:
        
        mes = Integer.parseInt(cmbMes.getItemAt(cmbMes.getSelectedIndex()));
        
    }//GEN-LAST:event_cmbMesActionPerformed

    private void cmbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClienteActionPerformed
        // TODO add your handling code here:
        
        String c = cmbCliente.getItemAt(cmbCliente.getSelectedIndex());
        txtCliente.setText(c.substring(0, c.indexOf(")")+1));
        
    }//GEN-LAST:event_cmbClienteActionPerformed

        
    private boolean buscarLibroEnLista(String serie){
        int l = modelCL.getSize();
        boolean existe = false;
        String s, serieEnLista;
        // el valor del item libro es sumado o restado al acumualo 
        //String valorItem = lC.substring(lC.indexOf("+")+2,largo).trim();
        // controla que siempre haya un autor seleccionado
        while(l>0){
            s = String.valueOf(modelCL.get(l-1));
            serieEnLista = s.substring(s.indexOf("(") + 1, s.indexOf(")")).trim();
            if (serieEnLista.equals(serie)){
                existe = true;
                JOptionPane.showMessageDialog(null, "Error, Serie ya esta en lista: "+serieEnLista, "",1);
                break;
            }
            l--;
        }
        return existe;
    }
    
    
    
    
    private void txtSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerieActionPerformed
        // TODO add your handling code here:
        
        if(esNumero(txtSerie.getText())){
            ControladorLibros cL = new ControladorLibros();
            Libros libroEncontrado = cL.leer(txtSerie.getText());
            if(libroEncontrado!=null){
                if(!buscarLibroEnLista(txtSerie.getText().trim())){
                txtTituloLibro.setText(libroEncontrado.getTitulo());
                txtPrecio.setText(String.valueOf(libroEncontrado.getPrecioReferencia()));
                txtPrecio.setHorizontalAlignment(JTextField.RIGHT);
                txtSerie.setEditable(false);
                txtPrecio.setEnabled(true);
                txtCantidad.setEnabled(true);
                txtTituloLibro.setEnabled(true);
                txtTituloLibro.setEditable(false);
                antiguoStock = libroEncontrado.getStock();
                enArriendo = libroEncontrado.getEnArriendo();
                int stockReal = antiguoStock - enArriendo;
                labelStock.setText("en Stock: "+String.valueOf(stockReal));
                }else{
                    cambiarSerie();
                }
            }else{
                //libro no existe se puede grabar sin datos
                //txtTitulo.setText(JOptionPane.showInputDialog (null,
                       // "Título para asociar a Serie ?","Libro No Hallado",JOptionPane.QUESTION_MESSAGE));
                JOptionPane.showMessageDialog(null, "Error!, LIBRO SEGUN SERIE NO EXISTE", "",1);
            }
            
        }else{
            //no es serie válido
            JOptionPane.showMessageDialog(null, "Error!, SERIE DEBE SER NUMERICO", "",1);
        }
        
    }//GEN-LAST:event_txtSerieActionPerformed

    private void jListLibrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListLibrosMouseClicked
        // TODO add your handling code here:
        String libroBorrar=jListLibros.getSelectedValue();
        //jListLibrosComprados.getSelectedIndex());
        if(libroBorrar!=null){
            jListLibros.setModel(modelListA(libroBorrar));
        }
        
    }//GEN-LAST:event_jListLibrosMouseClicked

    private void txtFolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFolioActionPerformed
        // TODO add your handling code here:
   
        }
        
    {       
    }//GEN-LAST:event_txtFolioActionPerformed

    private void txtNetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNetoActionPerformed

    private void btnCambiaSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiaSerieActionPerformed
        // TODO add your handling code here:
        cambiarSerie();
    }//GEN-LAST:event_btnCambiaSerieActionPerformed

    private void txtIvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIvaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIvaActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
        txtCantidad.setHorizontalAlignment(JTextField.RIGHT);
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void txtDependienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDependienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDependienteActionPerformed

    private void cmbDependienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDependienteActionPerformed
        // TODO add your handling code here:
        
        String d = cmbDependiente.getItemAt(cmbDependiente.getSelectedIndex());
        txtDependiente.setText(d.substring(0, d.indexOf(")")+1));

        
    }//GEN-LAST:event_cmbDependienteActionPerformed

    private void btnActualizarDependienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarDependienteActionPerformed
        // TODO add your handling code here:
      
        poblarDependientes();
        
    }//GEN-LAST:event_btnActualizarDependienteActionPerformed

    private void btnAgregaDependienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregaDependienteActionPerformed
        // TODO add your handling code here:
       
        if (!fp.isVisible()){
            fp.setVisible(true);    
        }
    }//GEN-LAST:event_btnAgregaDependienteActionPerformed

    private void jTableLibrosVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLibrosVentasMouseClicked
        // TODO add your handling code here:

        
        txtSerie.setText(String.valueOf(modelTableVentas.getValueAt(jTableLibrosVentas.getSelectedRow(),0)));
        txtTituloLibro.setText(String.valueOf(modelTableVentas.getValueAt(jTableLibrosVentas.getSelectedRow(),2)));

    }//GEN-LAST:event_jTableLibrosVentasMouseClicked

    private void txtSerieKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSerieKeyReleased
        // TODO add your handling code here:
        llenarTablaConLibros("id_libro_serie",txtSerie.getText());

    }//GEN-LAST:event_txtSerieKeyReleased

    private void txtTotalParcialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalParcialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalParcialActionPerformed

    private void cambiarSerie(){
        txtTituloLibro.setText("");
        txtCantidad.setText("");
        txtPrecio.setText("");
        txtSerie.setText("");
        txtCantidad.setEnabled(false);
        txtPrecio.setEnabled(false);
        txtSerie.setEditable(true);
        labelStock.setText("");
        llenarTablaConLibros("titulo","");
    } 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FVentasLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FVentasLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FVentasLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FVentasLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FVentasLibros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarCliente;
    private javax.swing.JButton btnActualizarDependiente;
    private javax.swing.JButton btnAgregaCliente;
    private javax.swing.JButton btnAgregaDependiente;
    private javax.swing.JButton btnAgregarLibro;
    private javax.swing.JButton btnCambiaSerie;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrarVenta;
    private javax.swing.JComboBox<String> cmbCliente;
    private javax.swing.JComboBox<String> cmbCuotas;
    private javax.swing.JComboBox<String> cmbDependiente;
    private javax.swing.JComboBox<String> cmbDia;
    private javax.swing.JComboBox<String> cmbFormaPago;
    private javax.swing.JComboBox<String> cmbMes;
    private javax.swing.JComboBox<String> cmbYear;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jListLibros;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JTable jTableLibrosVentas;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel labelStock;
    private javax.swing.JLabel lbFechaSistema;
    public static javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtDependiente;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtFolio;
    private javax.swing.JTextArea txtGlosa;
    private javax.swing.JTextField txtIva;
    private javax.swing.JTextField txtNeto;
    public static javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtSerie;
    private javax.swing.JTextField txtSubtotalVenta;
    public static javax.swing.JTextField txtTituloLibro;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotalParcial;
    // End of variables declaration//GEN-END:variables
}
