/**
 * fecha de creacion: junio de 2018
 * nombre: FFrameListaPersonas
 * Su función lista de clientes
 * entrada null
 * salida null
 * @author: braulio valdes 
 */
package vista;

import controlador.ControladorPersona;
import java.util.ArrayList;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import modelo.Personas;


/**
 *
 * @author BRAULIOMARIANO
 */
public class JFrameListaPersonas extends javax.swing.JFrame {

    /**
     * Creates new form JFrameListaCompras
     */
    
    String [] titulos = {"RUT","NOMBRE","FECHA CONTRATO","INCORPORACION","TIPO","ESTADO"};
    String [] campos = new String [6];
    DefaultTableModel modelTable;
    
    public JFrameListaPersonas() {
        initComponents();
        this.setAlwaysOnTop(true);
        this.setLocationRelativeTo(null);
        llenarTablaConPersonas();
    }
    void llenarTablaConPersonas(){
        modelTable = new DefaultTableModel(null,titulos);
        ControladorPersona cpersonas = new ControladorPersona();
        ArrayList<Personas> persona;
        persona = cpersonas.consultarTodo();
        if(persona!=null){
            int largo=persona.size(),tp,e;
            String dd,mm,aa;
            while (largo>0){
                //extrae datos del arraylist para poblar tabla personas             
                campos[0]=String.valueOf(persona.get(largo-1).getId_persona_rut())+"-"+
                                   persona.get(largo-1).getDv_persona();
                
                campos[1]=persona.get(largo-1).getNombre()+" "+persona.get(largo-1).getApaterno()+
                            " "+persona.get(largo-1).getAmaterno();                
                dd=String.valueOf(persona.get(largo-1).getDia_contrato());
                mm=String.valueOf(persona.get(largo-1).getMes_contrato());
                aa=String.valueOf(persona.get(largo-1).getYear_contrato());
                campos[2]=dd+"/"+mm+"/"+aa;
                aa=String.valueOf(persona.get(largo-1).getDia_incorporado());
                mm=String.valueOf(persona.get(largo-1).getMes_incorporado());
                aa=String.valueOf(persona.get(largo-1).getYear_incorporado());
                campos[3]=dd+"/"+mm+"/"+aa;
                tp=persona.get(largo-1).getTipo_persona();
                if(tp==0){
                    campos[4]="Cliente";
                }else{
                    if(tp==1){
                        campos[4]="Dependiente";
                    }else{
                        campos[4]="Cliente y Dependiente";
                    }
                }
                e=persona.get(largo-1).getEstado();
                if(e==0){
                    campos[5]="Eliminado";
                }else{
                    if(e==1){
                        campos[5]="Vigente";
                    }else{
                        campos[5]="Bloqueado por arriendo en mora";
                    }
                }
                modelTable.addRow(campos);
                largo--;
            }
         jTablePersonas.removeAll();
         jTablePersonas.setModel(modelTable);
                 //ALINEA CELDAS TABLAS
         DefaultTableCellRenderer alinear = new DefaultTableCellRenderer();
         alinear.setHorizontalAlignment(SwingConstants.RIGHT);//.LEFT .RIGHT .CENTER
         jTablePersonas.getColumnModel().getColumn(0).setCellRenderer(alinear);
         jTablePersonas.getColumnModel().getColumn(1).setCellRenderer(alinear);
         jTablePersonas.getColumnModel().getColumn(2).setCellRenderer(alinear);
         jTablePersonas.getColumnModel().getColumn(3).setCellRenderer(alinear);
         jTablePersonas.getColumnModel().getColumn(4).setCellRenderer(alinear);
         jTablePersonas.getColumnModel().getColumn(5).setCellRenderer(alinear);
        }
    }

    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePersonas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(200, 100));
        setUndecorated(true);

        jTablePersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTablePersonas);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText(" < L I S T A D O     D E     V E N T A S     E F E C T U A D A S > ");

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(168, 168, 168)
                        .addComponent(jLabel1)
                        .addGap(0, 278, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameListaPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameListaPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameListaPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameListaPersonas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameListaPersonas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePersonas;
    // End of variables declaration//GEN-END:variables
}
