/**
 * fecha de creacion: junio de 2018
 * nombre: FFrameListaCompras
 * Su función lista historial compras
 * entrada null
 * salida null
 * @author: braulio valdes 
 */
package vista;

import controlador.ControladorCompras;
import java.util.ArrayList;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import modelo.Compras;

/**
 *
 * @author BRAULIOMARIANO
 */
public class JFrameListaCompras extends javax.swing.JFrame {

    /**
     * Creates new form JFrameListaCompras
     */
    
    String [] titulos = {"Id COMPRA","FOLIO","RUT DISTRIBUIDOR","TOTAL CON IVA","FECHA","HORA","N°ITEMS"};
    String [] campos = new String [7];
    DefaultTableModel modelTable;
    
    
    
    
    
    public JFrameListaCompras() {
        initComponents();
        this.setAlwaysOnTop(true);
        this.setLocationRelativeTo(null);
        llenarTablaCompras();
    }
    void llenarTablaCompras(){
        modelTable = new DefaultTableModel(null,titulos);
        
        ControladorCompras cCompras = new ControladorCompras();
        ArrayList<Compras> compras;
        compras = cCompras.consultarTodo();
        String fechaCompra;
        String horaCompra;
        // alinear texto celdas de una tabla
        DefaultTableCellRenderer Alinear = new DefaultTableCellRenderer();
        
        if(compras!=null){
            int largo=compras.size();
            while (largo>0){
                
                campos[0]=String.valueOf(compras.get(largo-1).getId_compras());
                campos[1]=String.valueOf(compras.get(largo-1).getFolio_factura());
                campos[2]=String.valueOf(compras.get(largo-1).getId_distribuidor());
                campos[3]=String.valueOf(compras.get(largo-1).getTotal());
                fechaCompra=String.valueOf(compras.get(largo-1).getDia_compra());
                fechaCompra=fechaCompra+"/"+String.valueOf(compras.get(largo-1).getMes_compra());
                fechaCompra=fechaCompra+"/"+String.valueOf(compras.get(largo-1).getYear_compra());
                campos[4]=fechaCompra;
                horaCompra=String.valueOf(compras.get(largo-1).getHora_compra());
                horaCompra=horaCompra+":"+String.valueOf(compras.get(largo-1).getMinuto_compra());
                horaCompra=horaCompra+":"+String.valueOf(compras.get(largo-1).getSegundo_compra());
                campos[5]=horaCompra;
                campos[6]=String.valueOf(compras.get(largo-1).getNumero_libros());
                
                modelTable.addRow(campos);
                
                largo--;
            }
        jTableCompras.removeAll();
        jTableCompras.setModel(modelTable);
        Alinear.setHorizontalAlignment(SwingConstants.RIGHT);//.LEFT .RIGHT .CENTER
        jTableCompras.getColumnModel().getColumn(0).setCellRenderer(Alinear);
        jTableCompras.getColumnModel().getColumn(1).setCellRenderer(Alinear);
        jTableCompras.getColumnModel().getColumn(2).setCellRenderer(Alinear);
        jTableCompras.getColumnModel().getColumn(4).setCellRenderer(Alinear);
        jTableCompras.getColumnModel().getColumn(5).setCellRenderer(Alinear);
        jTableCompras.getColumnModel().getColumn(6).setCellRenderer(Alinear);
        jTableCompras.getColumnModel().getColumn(3).setCellRenderer(Alinear);
                }
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCompras = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(200, 100));
        setUndecorated(true);

        jTableCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableCompras);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText(" < L I S T A D O     D E     C O M P R A S     E F E C T U A D A S > ");

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(168, 168, 168)
                        .addComponent(jLabel1)
                        .addGap(0, 261, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameListaCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameListaCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameListaCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameListaCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameListaCompras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCompras;
    // End of variables declaration//GEN-END:variables
}
